CBlog_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('privacy-policy/', user_views.privacy_policy, name='privacy_policy'),
    path('termsandconditions/', user_views.tnc, name='tnc'),
    path('accounts/', include('allauth.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.UserProfileListView.as_view(), name='profile'),
    path('profile/settings', user_views.profile_settings, name='profile_settings'),
    path('profile/followers', user_views.FollowersListView.as_view(), name='followers'),
    path('profile/following', user_views.FollowingListView.as_view(), name='following'),
    path('profile/toggle-follower/<int:pk>/', user_views.ToggleFollower.as_view(), name='toggle_follower'),
    path('profile/toggle-follower/js', user_views.toggle_follower_js, name='toggle_follower_js'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=CustomAuthForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('<int:pk>/account_delete/', user_views.UserDeleteView.as_view(), name='user_confirm_delete'),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
        name='password_reset'),
     path('password-reset/done', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),
     path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),
     path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'users.views.handler400'
handler404 = 'users.views.handler404'
handler500 = 'users.views.handler500'

blog/urls.py
from django.urls import path 
from . views import (
	PostListView, 
	PostDetailView, 
	LatestCommentsPostDetailView,
	PostCreateView, 
	PostUpdateView,
	PostDeleteView,
	UserPostListView,
	UserPostByCatListView,
	SearchResultsView,
	UserResultsView,
	CategoryResultsView,
	like_unlike_post,
	del_comment,
	del_parent_comment,
	del_com_temp,
	load_more_comments_detail,
	load_more_comments_detail_bylatest,
	CommentReplyView,
	post_comment_detail_view,
	load_more_replies_detail_bylatest,
	PostNotification,
	CommentReplyNotification,
	FollowNotification,
	RemoveNotification,
	ThreadNotification,
	ListThread,
	CreateThread,
	ThreadView,
	CreateMessage,
	profile_to_thread,	
)
from . import views

urlpatterns = [
	path('', PostListView.as_view(), name='blog-home'),
	path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
	path('user/<str:username>/category/<str:category>/', UserPostByCatListView.as_view(), name='user-posts-bycat'),
	path('search/', UserResultsView.as_view(), name='user_results'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/load-more-comments-detail/', views.load_more_comments_detail, name='load-more-comments-detail'),
	path('post/load-more-comments-detail-bylatest/', views.load_more_comments_detail_bylatest, name='load-more-comments-detail-bylatest'),
	path('post/<int:pk>/latest/', LatestCommentsPostDetailView.as_view(), name='latest-comment-post-detail'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('post/search/', SearchResultsView.as_view(), name='search-results'),
	path('category/<str:category>/', CategoryResultsView.as_view(), name='cat-results'),
	path('post/liked/', views.like_unlike_post, name='like-post-view'),
	path('post/comment/', views.comment_post, name='comment-post-view'),
	path('post/<int:post_pk>/comment/<int:comment_pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
	path('post/<int:post_pk>/comment/<int:comment_pk>', views.post_comment_detail_view, name='post-comment-detail'),
	path('post/load-more-replies-detail-bylatest/', views.load_more_replies_detail_bylatest, name='load-more-replies-detail-bylatest'),
	path('post/comment/like/', views.like_unlike_comment, name='like-comment-view'),
	path('post/comment/<int:pk>/delete/', views.del_comment, name='comment-delete'),
	path('post/parent-comment/<int:pk>/delete/', views.del_parent_comment, name='parent-comment-delete'),
	path('post/commenttemp/<int:pk>/delete/', views.del_com_temp, name='comment-delete-temp'),
	path('notification/<int:notification_pk>/post/<int:post_pk>/', PostNotification.as_view(), name='post-notification'),
	path('notification/<int:notification_pk>/post/<int:post_pk>/<int:comment_pk>/', CommentReplyNotification.as_view(), name='comment-reply-notification'),
	path('notification/<int:notification_pk>/profile/<int:profile_pk>/', FollowNotification.as_view(), name='follow-notification'),
	path('notification/<int:notification_pk>/thread/<int:thread_pk>/', ThreadNotification.as_view(), name='thread-notification'),
	path('notification/delete/<int:notification_pk>/', RemoveNotification.as_view(), name='notification-delete'),
	path('inbox/', ListThread.as_view(), name='inbox'),
	path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
	path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
	path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
	path('inbox/<int:profile_pk>/profile-message/', views.profile_to_thread, name='profile-message'),
	path('about/', views.about, name='blog-about'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from users.models import Profile
from django.urls import reverse
import re


class Category(models.Model):
	category_name = models.CharField(max_length=50, default='general coding', verbose_name="Categories")

	def __str__(self):
		return self.category_name 

	def get_absolute_url(self):
		return reverse('blog-home')

class Post(models.Model):
	title = models.CharField(max_length=100, help_text="100 characters or less")
	content = models.TextField(max_length=3000, help_text="3k characters or less")
	category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
	ip_address = models.CharField(max_length=25, default='00.000.000.000', blank=True, null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

	def get_youtube_urls(self):
		urls = []
		youtube_regex = (
			r'(https?://)?(www\.)?'
			'(youtube)\.(com)/'
			'(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})')

		matches = re.findall(youtube_regex, self.content)

		for url in matches:
			urls.append(url[5])

		return urls

	def num_likes(self):
		return self.liked.all().count()
	num_likes.short_description = 'Total Likes'

	def num_comments(self):
		return self.comment_set.all().count()

class PostImage(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='post_pics', blank=True, null=True)

	def __str__(self):
		return self.post.title

	def save(self, *args, **kwargs):
		if PostImage.objects.filter(post=self.post).count() >= 7:
			return
		else:
			super(PostImage, self).save(*args, **kwargs)

LIKE_CHOICES = (
	('Like', 'Like'),
	('Unlike', 'Unlike'),
)

class Like(models.Model):
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	value = models.CharField(choices=LIKE_CHOICES, max_length=8)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)
	ip_address = models.CharField(max_length=25, default='00.000.000.000', blank=True, null=True)

	def __str__(self):
		return f"{self.user}-{self.post}-{self.value}"

class Comment(models.Model):
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	body = models.TextField(max_length=300)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)
	liked = models.ManyToManyField(Profile, blank=True, related_name='com_likes')
	parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
	ip_address = models.CharField(max_length=25, default='00.000.000.000', blank=True, null=True)

	def __str__(self):
		return f"Comment:{self.user}-{self.post}-{self.id}"

	def post_id(self):
		return self.post.id

	def post_author(self):
		return self.post.author

	def num_likes(self):
		return self.liked.all().count()

	def num_children(self):
		return Comment.objects.filter(parent=self).all().count()

	@property 
	def children(self):
		return Comment.objects.filter(parent=self).order_by('-created').all()

	@property
	def is_parent(self):
		if self.parent is None:
			return True
		return False

class CommentLike(models.Model):
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	value = models.CharField(choices=LIKE_CHOICES, max_length=8)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)
	ip_address = models.CharField(max_length=25, default='00.000.000.000', blank=True, null=True)

	def __str__(self):
		return f" | CommentLike({self.user}-{self.comment}-{self.value})"

class Notification(models.Model):
	# 1 = Like, 2 = Comment, 3 = Follow, 4 = Message
	notification_type = models.IntegerField()
	to_user = models.ForeignKey(User, related_name='notification_to', on_delete=models.CASCADE, null=True)
	from_user = models.ForeignKey(User, related_name='notification_from', on_delete=models.CASCADE, null=True)
	post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
	comment = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
	thread = models.ForeignKey('ThreadModel', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)
	user_has_seen = models.BooleanField(default=False)

class ThreadModel(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')

	def __str__(self):
		return f"Message thread between user:{self.user} and receiver:{self.receiver}"

class MessageModel(models.Model):
	thread = models.ForeignKey('ThreadModel', related_name='+', on_delete=models.CASCADE, blank=True, null=True)
	sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
	body = models.CharField(max_length=1000)
	image = models.ImageField(upload_to='message_photos', blank=True, null=True)
	date = models.DateTimeField(default=timezone.now)
	is_read = models.BooleanField(default=False) 

blog/forms.py
from django import forms
from .models import Post, PostImage, Category, Comment, MessageModel
from django.forms import inlineformset_factory
from django.forms.widgets import ClearableFileInput


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Add images', required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = PostImage
        fields = ['image']

ImageFormSet = inlineformset_factory(Post, PostImage, form=ImageForm, extra=1, can_delete=False)

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', 
                            widget=
                            forms.Textarea(
                                attrs={'placeholder': 'Write your reply \nMax 300 characters.', 
                                'rows': 1, 'cols': 25}))
    class Meta:
        model = Comment 
        fields = ['body']

class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'placeholder': '@'}))

class MessageForm(forms.ModelForm):
    body = forms.CharField(label='', max_length=1000)

    image = forms.ImageField(label='Add an image', required=False)

    class Meta:
        model = MessageModel
        fields = ['body', 'image']

blog/templates/blog/about.html
{% extends 'blog/base_secondary.html' %}
{% load static %}

{% block content %}

	<h1><center><a href="{% url 'blog-home' %}" style="color: black;">ByteTheApple.com</a></center></h1>

<br>
	<p style="font-size: 1.2rem;">
	The bite in the apple symbolizes the forbidden fruit from the Garden Of Eden. When Eve took a bite out of the apple, she gained knowledge of good and evil. During the past century, human advancement on technology has evolved to a point our ancestors could not have fathomed. This technology can be used either for the development or destruction of mankind. It is ultimately in the hands of the individual whether one chooses to do good or bad with this power.</p>

<p style="font-size: 1.2rem;">ByteTheApple disseminates information for engineers, who are the developers of this power, by offering a fully functional, full stack social media platform. ByteTheApple welcomes you to the Network, a private community of developers and technologists around the world, and invites you to participate in the community by sharing knowledge with your peers and colleagues.</p>

<p style="font-size: 1.2rem;"><em>
"Technology is nothing. What's important is that you have a faith in people, <br>that they're basically good and smart, and if you give them tools, <br>they'll do wonderful things with them." <br>- Steve Jobs
</em></p>

{% if request.user.is_authenticated %}
<h4 style="float:right"><a href="{% url 'blog-home' %}">Start Exploring</a></h4>
{% else %}
<h4 style="float:right"><a href="{% url 'login' %}">Get Started</a></h4>
{% endif %}

	<center><img class="rounded" src="https://bytetheapple.s3.us-west-1.amazonaws.com/static/images/sm_logos/about-1.png" style="height:300px; width:300px;"></center>

<!-- /media/sm_logos/about-1.png -->

{% block news_content %}
{% endblock %}
{% endblock content %}

blog/templates/blog/comment_confirm_delete_template.html
<!-- COMMENT DELETE FORM INSIDE MODAL FOR JQUERY INFINITE SCROLL, NEW COMMENT -->

<div class="modal comdelete" id="commentdeleteModal-00" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the comment? <br>
        This can’t be undone.</p>
      </div>
      <div class="modal-footer">
    		<form action=" " method="POST" class="comdelete-form-temp" id="">
    			{% csrf_token %}
    			<div class="form-group">
      		  <button class="btn btn-danger" type="submit">Delete</button>
            <button type="button" class="btn btn-secondary closebtn" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>	
    </div>
  </div>
</div>

blog/templates/blog/comments.html
{% load static %}
{% load custom_tags %}

<!-- HTML FOR COMMENTS -->

{% for comment in post.comment_list|slice:"0:7" %}
{% if comment.is_parent %}
<div class="clist" id="clist{{ comment.id }}" >
	<article class="media comment-section">	
	<a class="mr-2 comment-user" href="{% url 'user-posts' comment.user %}">	
	<img class="rounded-circle comment-img" src="{{ comment.user.image.url }}"></a>
		<div class="media-body mt-1">
			<div class="article-metadata">
				<a class="mr-2 text-dark profile-link comment-user" href="{% url 'user-posts' comment.user %}">{{ comment.user.user.username }}</a>
				<small class="text-muted comment-created" style="float:right;">
					{% if comment.created|timesince|upto == "show_date" %}
					{{ comment.created|date:"F d, Y" }}
					{% elif comment.created|timesince|upto == "Just Now" %}
					{{ comment.created|timesince|upto }}
					{% else %}
					{{ comment.created|timesince|upto }} ago
					{% endif %}
				</small>
				<p class="comment-content">{{ comment.body|urlizetrunc:26 }}</p>
			</div>
			<div class="btn-group llc-btn">
			<form action="{% url 'like-comment-view' %}" method="POST" class="comlike-form" id='{{ comment.id }}'>
				{% csrf_token %}
				<input type="hidden" name="comment_id" value="{{ comment.id }}" class="cl-input"> 
				{% if request.user.is_authenticated %}
				{% if request.user.profile in comment.liked.all %}
					<button type="submit" class="btn btn-liked1 btn-sm py-0 com-like" id="like-btn{{ comment.id }}" style="font-size: 0.8em;">Liked <span class="like-icon"><i class="fa fa-heart"></i></span></button>
				{% else %}
					<button type="submit" class="btn btn-like0 btn-sm py-0 com-like" id="like-btn{{ comment.id }}" style="font-size: 0.8em;">Like <span class="like-icon"><i class="fa fa-heart"></i></span></button>
				{% endif %}
				{% else %}
					<a href="{% url 'login' %}" class="btn btn-like0 btn-sm py-0" style="font-size: 0.8em;">Like <span class="like-icon"><i class="fa fa-heart"></i></span></a>
				{% endif %}

				<!-- Button trigger modal - Shows likes list of users -->
				<button type="button" class="btn btn-outline-dark btn-sm py-0 com-modal like-count{{ comment.id }}" data-toggle="modal" style="font-size: 0.8em;" data-target="#commentlikesModalLong-{{ comment.id }}">
				  {{ comment.num_likes }} <small><i class="fa fa-heart fa-heart-blue"></i></small>
				</button>

				<!-- Modal -->
				<div class="modal fade cmodal" id="commentlikesModalLong-{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="commentlikesModalLongTitle" aria-hidden="true">
				  <div class="modal-dialog" role="document">
					<div class="modal-content">
					  <div class="modal-header">
						<h5 class="modal-title" id="commentlikesModalLongTitle">Liked by</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					  </div>
					  <div class="modal-body liked-list{{ comment.id }}">
						{% for user in comment.liked.all %}
						<div id="cl{{ user.user.username }}">
							<ul class="list-unstyled">
								<li>
									<a href="{% url 'user-posts' user %}">
									<img class="rounded-circle article-img" src="{{ user.image.url }}"></a>
									<a class="mr-2 badge badge-light" href="{% url 'user-posts' user %}">{{ user }}</a>
								</li>
							</ul>
						</div>
						{% endfor %}
					  </div>
					</div>
				  </div>
				</div>
			<a href="{% url 'post-comment-detail' post_pk=post.pk comment_pk=comment.pk %}" class="btn btn-outline-dark btn-sm py-0" style="font-size: 0.8em;">
				{% if comment.children.count == 0 %}
				0 <small><i class="fa fa-solid fa-comment"></i></small>
				{% else %}	
				{{ comment.children.count }} <small><i class="fa fa-solid fa-comment"></i></small>
				{% endif %}
				</a>
			</form>
			</div>
			
			{% if request.user == comment.user.user %}
			<div class="btn-group dropdown" style="float:right;">
				<button class="btn ud-action-button dropdown-toggle mt-n1 btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   				•••</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<!-- Button trigger modal - Delete Button -->
					<button class="btn text-danger btn-sm dropdown-item py-0 delete-btn{{ comment.id }}" style="font-size: 0.8em" data-toggle="modal" data-target="#commentdeleteModal-{{ comment.id }}">Delete <i class="fa fa-trash"></i></button>
				</div>
			{% include 'blog/comment_confirm_delete.html' %}
			</div>
			{% endif %}
			
		</div>
	</article>
</div>
{% endif %}
{% endfor %}

blog/templates/blog/create_thread.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- HTML FOR NEW THREAD IN MESSAGES -->

{% block content %}

<div class="container content-section">
	<div class="row">
		<div class="col-md-12 p-5">
			<a href="{% url 'inbox' %}" class="btn button-empty"> &lt Back to your Inbox</a>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Start A Message</h3>
		</div>
	</div>
	<div class="row justify-content-center mt-3 mb-5">
		<div class="col-md-5 col-sm-12">
			{% if messages %}
			{% for message in messages %}
			<div class="alert alert-danger">
				{{ message }}
			</div>
			{% endfor %}
			{% endif %}
			<form method="POST">
				{% csrf_token %}
				<p>Enter the username for the person you would like to message</p>
				{{ form|crispy }}
				<div class="d-grid gap-2">
					<button class="btn button mt-3" type="submit">Continue</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% block news_content %}
{% endblock %}
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load custom_tags %}

<!-- HTML FOR HOME PAGE -->

{% block content %}
	
	{% for post in posts %}
	<article class="media content-section shadow">
		<a class="mr-2" href="{% url 'user-posts' post.author.username %}">
			<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"></a>
		<div class="media-body">

		{% include 'blog/posts_main.html' %}

		{% if request.user.is_authenticated %}
		<br>
		<form action="{% url 'comment-post-view' %}" method="POST" class="com-form" id="{{ post.id }}">
			{% csrf_token %}
			<input type="hidden" name="post_id" value="{{ post.id }}">
			{{ c_form|crispy }}
			<button type="submit" class="button btn-sm mt-n2 com-btn mx-auto d-block" id="{{ post.pk }}" name="submit_c_form" style="float:right;">
				Comment 
			</button>
		</form>
		{% else %}
		<a href="{% url 'login' %}" class="btn btn-sm button mt-n2" style="float:right;">Comment</a>
		{% endif %}
		
		{% if post.comment_list %}
		<button class="show-replies-button button-empty btn-sm py-0 mx-auto d-block btn-block">Show replies</button>
    	<div class="comment-box" id="comment-box-{{ post.id }}">

			{% if post.comment_list|length|gtoe:7 %}
			<a href="{% url 'latest-comment-post-detail' post.id %}" class="btn btn-outline-secondary btn-sm py-0" style="font-size: 0.8em;">Sort By Latest Comments</a>
			<h6 class="text-center">showing top comments</h6>
			{% endif %}

			<div class="comment-list com-list{{ post.id }}" id="{{ post.pk }}">
				{% include 'blog/comments.html' %}
			</div>

			{% if post.comment_list|length|gtoe:7 %}
			<br>
			<a href="{% url 'post-detail' post.id %}" class="btn btn-outline-secondary btn-sm py-0 mx-auto d-block" style="font-size: 0.8em;">Show more replies</a> 
			{% endif %}
		</div>
		{% else %}
		<br><br>
		<div class="comment-list com-list{{ post.id }}" id="{{ post.pk }}">
		</div>
		{% endif %}

		</div>
	</article>

	{% endfor %}

	{% include 'blog/comment_template.html' %}

	{% include 'blog/pagination.html' %}

{% endblock content %}

{% block scripts %} 
<script src="{% static 'blog/base.js' %}"></script>
{% endblock scripts %}

 

blog/templates/blog/inbox.html
{% extends 'blog/base.html' %}
{% load static %}

<!-- HTML FOR INBOX IN MESSAGES -->

{% block content %}

<div class="container content-section">
	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Your Messages</h3><br>
			<h4>Welcome to your inbox!</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 p-5">
			<form method="GET" action="{% url 'create-thread' %}">
			<button class="btn btn-lg btn-block button" type="submit">New Message</button>
			</form>
		</div>		
	</div>
	{% for thread in threads.all %}
	<div class="row mb-3">
		<div class="card col-md-12 p-3 shadow-sm">
			<h5><img class="rounded-circle account-header-img" src="{{ thread.receiver.profile.image.url }}"> @{{ thread.receiver }}</h5>
			<a href="{% url 'thread' thread.pk %}" class="stretched-link"></a>
		</div>
	</div>
	{% endfor %}
</div>

{% block news_content %}
{% endblock %}
{% endblock content %}

blog/templates/blog/pagination.html
<!-- HTML FOR PAGE PAGINATION PER POST  -->

{% if is_paginated %}

	{% if page_obj.has_previous %}
	<a class="button-empty btn-sm mb-4" href="?page=1">First</a>
	<a class="button-empty btn-sm mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
	{% endif %}

	{% for num in page_obj.paginator.page_range %}
		{% if page_obj.number == num %}
		<a class="button btn-sm mb-4" href="?page={{ num }}">{{ num }}</a>
		{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
		<a class="button-empty btn-sm mb-4" href="?page={{ num }}">{{ num }}</a>
		{% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
	<a class="button-empty btn-sm mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
	<a class="button-empty btn-sm mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
	{% endif %}

{% endif %}

<!-- href="/?page=1" -->

blog/templates/blog/user_posts_bycategory.html
{% extends 'blog/base.html' %}
{% load static %}

<!-- HTML FOR ANY USER'S PROFILE PAGE WITH POSTS ORGANIZED BY CATEGORY -->

{% block content %}	

{% include 'blog/profile_header.html' %}
{% include 'blog/user_posts_main.html' %}
{% include 'blog/comment_template.html' %}
{% include 'blog/pagination.html' %}

{% block news_content %}
{% endblock %}
{% endblock content %}

{% block scripts %} 
<script src="{% static 'blog/base.js' %}"></script>
<script src="{% static 'blog/scroll_position.js' %}"></script>
{% endblock scripts %}